# Generated by Django 5.2.8 on 2026-02-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_profile_email_verified_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Gandhinagar', 'Gandhinagar'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('House', 'House'), ('Plot', 'Plot')], max_length=20)),
                ('size_sqft', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('age_of_property_years', models.IntegerField(default=0)),
                ('nearby_infrastructure_score', models.IntegerField(default=5)),
                ('distance_to_city_center_km', models.FloatField(default=0.0)),
                ('year', models.IntegerField(default=2024)),
                ('price_inr', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
