# Generated by Django 5.2.8 on 2026-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_profile_role_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
