# Generated by Django 5.2.8 on 2026-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_bugreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
