# Generated by Django 5.2.8 on 2026-03-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_property_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
